#!/bin/bash

if [ -z "$1" ]
then
    echo "[BUILD] Must pass a disk name to execute."
    exit -1
fi

cp $1 "$1_cpy"
echo "[BUILD] Copied $1 to $1_cpy"

echo "[BUILD] Compiling project"
gcc -g main.c -o project -w

echo "[BUILD] Executing compiled project with $1_cpy"
./project "$1_cpy"

echo "[BUILD] Removing $1_cpy and project"
rm "$1_cpy" project
